services:
  node:
    build:
      context: .
      target: base
    working_dir: /usr/src/app
    environment:
      HOST: 0.0.0.0
    networks: 
      - roast_development

networks:
  roast_development:
    external: true