services:
  node:
    ports:
      - 24678:24678
    volumes:
      - .:/usr/src/app:cached
    hostname: roast-nitro.dev.test
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      SSL_MODE: "full"
    networks: 
      - roast_development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roast-nitro.rule=Host(`roast-nitro.dev.test`)"
      - "traefik.http.routers.roast-nitro.entrypoints=websecure"
      - "traefik.http.routers.roast-nitro.tls=true"
      - "traefik.http.services.roast-nitro.loadbalancer.server.port=3000"
      - "traefik.http.services.roast-nitro.loadbalancer.server.scheme=http"
    command: "yarn dev"

networks:
  roast_development:
    external: true